"""MATRIZ DE ENTREGAVEIS — os 621 itens do proprietario, um a um (R69).

O proprietario entregou uma lista de 621 desenhos, quadros, planos e modelos e
pediu tudo, padronizado e completo. "Completo" nao se afirma: mede-se. Este
modulo e a medida. Cada item recebe UM status e UMA referencia:

  TEM      existe, e a referencia e uma prancha, uma vista do visualizador,
           um arquivo de saida ou um modulo do nucleo — a auditoria confere
           que a referencia existe de verdade
  PARCIAL  o dado esta no modelo ou numa prancha de outro assunto; a
           referencia diz onde, a nota diz o que falta
  FALTA    da para produzir do modelo e ainda nao foi produzido — e o
           backlog, e a auditoria o conta
  EXTERNO  depende de dado, servico ou obra que o modelo nao tem (levantamento
           contratado, certidao, as-built) — a nota diz de quem depende
  NA       nao se aplica a ESTA casa, e a nota diz por que; "nao se aplica"
           sem razao escrita e "esqueci" com outro nome

A lista tem muitos sinonimos (1 a 4, 46 a 48, 108 a 111, 449 a 453). Cada
sinonimo aponta para o item que o resolve, e entra na conta uma vez so: o
numero que importa e o de ENTREGAVEIS DISTINTOS, nao o de linhas.

Referencias: "PR-nn" prancha; "ENG:x" vista de engenharia do visualizador;
"3D" cena do visualizador; "OUT:arquivo" saida em out/; "nucleo/x" modulo;
"BOM" orcamento; "DOC:x" documento em docs/.
"""
from __future__ import annotations

BLOCOS = [
    ("A", 1, 30, "Levantamentos e estudos preliminares"),
    ("B", 31, 43, "Geotecnia, solo e terraplenagem"),
    ("C", 44, 80, "Arquitetura"),
    ("D", 81, 107, "Cortes e elevacoes"),
    ("E", 108, 123, "Esquadrias e aberturas"),
    ("F", 124, 145, "Marcenaria e mobiliario fixo"),
    ("G", 146, 174, "Estrutura"),
    ("H", 175, 228, "Steel frame"),
    ("I", 229, 249, "Eletrica"),
    ("J", 250, 256, "Energia solar"),
    ("K", 257, 271, "Hidraulica"),
    ("L", 272, 282, "Esgoto e ventilacao sanitaria"),
    ("M", 283, 294, "Aguas pluviais e drenagem"),
    ("N", 295, 300, "Gas"),
    ("O", 301, 315, "Climatizacao, ventilacao e exaustao"),
    ("P", 316, 328, "Telecomunicacoes, dados e automacao"),
    ("Q", 329, 338, "Seguranca eletronica"),
    ("R", 339, 346, "Prevencao e combate a incendio"),
    ("S", 347, 363, "Piscina"),
    ("T", 364, 379, "Areas externas e paisagismo"),
    ("U", 380, 390, "Fachadas e revestimentos"),
    ("V", 391, 401, "Impermeabilizacao e estanqueidade"),
    ("W", 402, 410, "Conforto termico e acustico"),
    ("X", 411, 431, "Detalhes construtivos"),
    ("Y", 432, 468, "Fabricacao e industrializacao"),
    ("Z", 469, 484, "Compatibilizacao"),
    ("AA", 485, 500, "BIM e modelos digitais"),
    ("AB", 501, 525, "Apresentacao e visualizacao"),
    ("AC", 526, 544, "Execucao de obra"),
    ("AD", 545, 560, "Orcamento, quantitativos e compras"),
    ("AE", 561, 574, "Qualidade, testes e inspecoes"),
    ("AF", 575, 595, "As-built e manutencao"),
    ("AG", 596, 621, "Documentacao geral do projeto"),
]

# (n, nome, status, referencia, nota). "=k" na nota = sinonimo do item k.
ITENS = [
    # ---- A. levantamentos e estudos preliminares
    (1, "Levantamento topografico", "EXTERNO", "pendencia 17", "=4"),
    (2, "Levantamento planimetrico", "EXTERNO", "pendencia 17", "=4"),
    (3, "Levantamento altimetrico", "EXTERNO", "pendencia 17", "=4"),
    (4, "Levantamento planialtimetrico", "EXTERNO", "pendencia 17",
     "topografia entrou como faixa declarada pelo proprietario (PR-47); a poligonal medida e contratada"),
    (5, "Cadastro do terreno", "TEM", "PR-01", "SITIO e CADASTRO no caso"),
    (6, "Cadastro de construcoes existentes", "NA", "SITIO", "lote vazio"),
    (7, "Levantamento de arvores e vegetacao", "TEM", "PR-32", "SITIO: sem arvore grande; paisagismo planta as novas"),
    (8, "Levantamento de postes, redes e interferencias", "EXTERNO", "pendencia 17", "entra com o planialtimetrico"),
    (9, "Levantamento de muros e divisas", "TEM", "PR-31", "gabarito e cantos com diagonal"),
    (10, "Levantamento fotografico", "EXTERNO", "proprietario", "nao entregue"),
    (11, "Planta de situacao", "TEM", "PR-01", ""),
    (12, "Planta cadastral", "TEM", "PR-01", "quadro cadastral e urbanistico"),
    (13, "Planta de orientacao solar", "TEM", "PR-19", ""),
    (14, "Estudo de insolacao", "TEM", "PR-19", ""),
    (15, "Estudo de sombreamento", "TEM", "3D", "sombra por hora e epoca na cena; PR-19"),
    (16, "Estudo de ventilacao natural", "TEM", "PR-49", "abertura por face e por ambiente (nucleo/ventilacao)"),
    (17, "Estudo de ventilacao cruzada", "TEM", "PR-49", "=16"),
    (18, "Estudo de conforto termico", "TEM", "PR-11", ""),
    (19, "Estudo de conforto acustico", "TEM", "PR-39", "PR-11 e PR-13"),
    (20, "Estudo de eficiencia energetica", "PARCIAL", "PR-41",
     "consumo e geracao no modelo; etiqueta PBE Edifica exige simulacao horaria — EXTERNO"),
    (21, "Estudo de implantacao", "TEM", "PR-01", "PR-31"),
    (22, "Estudo de acessos", "TEM", "PR-17", "rampa em PR-47"),
    (23, "Estudo de circulacao", "TEM", "PR-17", "nucleo/ocupacao mede a circulacao"),
    (24, "Estudo de vistas", "TEM", "PR-43", "PR-43 a PR-46"),
    (25, "Estudo de privacidade", "TEM", "PR-49", "janela a janela contra a divisa e o vizinho"),
    (26, "Estudo de ocupacao do terreno", "TEM", "PR-01", "nucleo/ocupacao"),
    (27, "Estudo de taxa de ocupacao", "TEM", "PR-09", "quadro urbanistico"),
    (28, "Estudo de coeficiente de aproveitamento", "TEM", "PR-09", ""),
    (29, "Estudo de areas permeaveis", "TEM", "PR-38", ""),
    (30, "Estudo preliminar volumetrico", "TEM", "PR-08", "3D"),
    # ---- B. geotecnia
    (31, "Planta de locacao dos furos de sondagem", "TEM", "PR-37", ""),
    (32, "Perfil geotecnico do terreno", "TEM", "PR-37", ""),
    (33, "Representacao grafica da sondagem", "TEM", "PR-37", ""),
    (34, "Planta de terraplenagem", "TEM", "PR-47", ""),
    (35, "Planta de corte e aterro", "TEM", "PR-47", "zero m3 alem da troca de solo, demonstrado"),
    (36, "Perfis longitudinais do terreno", "TEM", "PR-47", ""),
    (37, "Perfis transversais do terreno", "PARCIAL", "PR-47", "sem declividade transversal declarada: pendencia 17"),
    (38, "Mapa de cotas naturais", "TEM", "PR-47", "faixa de 1 % a 2 %"),
    (39, "Mapa de cotas projetadas", "TEM", "PR-47", "plataforma e piso acabado"),
    (40, "Planta de contencoes", "NA", "PR-47", "declividade de ate 2 %: sem contencao"),
    (41, "Detalhamento de muros de arrimo", "NA", "PR-47", "=40"),
    (42, "Detalhamento de taludes", "NA", "PR-47", "=40"),
    (43, "Planta de drenagem provisoria de obra", "FALTA", "", "entra na planta de canteiro"),
    # ---- C. arquitetura
    (44, "Planta de implantacao", "TEM", "PR-01", ""),
    (45, "Planta de locacao da construcao", "TEM", "PR-31", ""),
    (46, "Planta baixa arquitetonica", "TEM", "PR-02", "PR-03"),
    (47, "Planta baixa cotada", "TEM", "PR-02", "=46"),
    (48, "Planta baixa executiva", "TEM", "PR-02", "=46: 1:50 com cotas eixo a eixo"),
    (49, "Planta de layout", "TEM", "PR-04", "PR-42"),
    (50, "Planta mobiliada", "TEM", "PR-04", "=49"),
    (51, "Planta humanizada", "FALTA", "", "pisos e mobiliario com cor dos acabamentos"),
    (52, "Planta de circulacao", "TEM", "PR-17", ""),
    (53, "Planta de acessibilidade", "TEM", "PR-17", ""),
    (54, "Planta de fluxos", "TEM", "PR-17", ""),
    (55, "Planta de usos dos ambientes", "TEM", "PR-13", "categoria por ambiente"),
    (56, "Planta de areas", "TEM", "PR-09", "quadros de area nas plantas"),
    (57, "Planta de demolicao", "NA", "SITIO", "lote vazio"),
    (58, "Planta de construcao", "TEM", "PR-02", "e o caderno inteiro"),
    (59, "Planta de reforma", "NA", "SITIO", "obra nova"),
    (60, "Planta de ampliacao", "NA", "SITIO", "obra nova"),
    (61, "Planta de cobertura", "TEM", "PR-05", ""),
    (62, "Planta de telhado", "NA", "PR-05", "cobertura plana com platibanda"),
    (63, "Planta de forro", "TEM", "PR-16", ""),
    (64, "Planta de niveis de forro", "TEM", "PR-16", "altura por ambiente"),
    (65, "Planta de sancas e cortineiros", "FALTA", "", "cortineiro nas janelas de dormitorio (blackout no BOM)"),
    (66, "Planta de pisos", "TEM", "PR-24", "PR-30"),
    (67, "Planta de paginacao de pisos", "TEM", "PR-24", ""),
    (68, "Planta de paginacao de paredes", "PARCIAL", "PR-22", "banhos em PR-22/23; falta cozinha, gourmet e lavanderia"),
    (69, "Planta de revestimentos", "TEM", "PR-30", ""),
    (70, "Planta de acabamentos", "TEM", "PR-30", ""),
    (71, "Mapa de materiais", "TEM", "PR-30", "PR-13, PR-36"),
    (72, "Mapa de cores", "FALTA", "", "paleta por superficie, fachada e interior"),
    (73, "Mapa de texturas", "FALTA", "", "=72"),
    (74, "Mapa de rodapes", "FALTA", "", "quantidade no BOM; falta o mapa"),
    (75, "Mapa de soleiras", "FALTA", "", "detalhe em PR-10; falta o mapa por porta"),
    (76, "Mapa de peitoris", "FALTA", "", "peitoril por esquadria no caso; falta o mapa"),
    (77, "Planta de impermeabilizacao", "PARCIAL", "PR-22", "banhos, piscina (PR-34) e cobertura (PR-05); falta a prancha unica"),
    (78, "Planta de juntas de movimentacao", "FALTA", "", "juntas de fachada no BOM; falta o desenho"),
    (79, "Planta de juntas de dilatacao", "NA", "PR-37", "radier de 19 x 13 m: sem junta de dilatacao"),
    (80, "Planta de estanqueidade", "PARCIAL", "PR-13", "exigencias por familia; falta a prancha de estanqueidade"),
    # ---- D. cortes e elevacoes
    (81, "Corte longitudinal", "TEM", "PR-06", ""),
    (82, "Corte transversal", "TEM", "PR-06", ""),
    (83, "Corte geral da residencia", "TEM", "PR-06", "=81"),
    (84, "Corte da garagem", "FALTA", "", "cortes por ambiente"),
    (85, "Corte da escada", "TEM", "PR-25", ""),
    (86, "Corte da cozinha", "FALTA", "", "=84"),
    (87, "Corte da area gourmet", "FALTA", "", "=84"),
    (88, "Corte da suite master", "FALTA", "", "=84"),
    (89, "Corte dos banheiros", "FALTA", "", "=84"),
    (90, "Corte da piscina", "TEM", "PR-34", "PR-10 det. 3"),
    (91, "Corte do terreno", "TEM", "PR-47", ""),
    (92, "Corte estrutural", "TEM", "PR-20", ""),
    (93, "Corte construtivo de fachada", "PARCIAL", "PR-10", "parede externa 1:5; falta o corte do radier a platibanda"),
    (94, "Fachada frontal", "TEM", "PR-07", ""),
    (95, "Fachada posterior", "TEM", "PR-07", ""),
    (96, "Fachada lateral direita", "TEM", "PR-07", ""),
    (97, "Fachada lateral esquerda", "TEM", "PR-07", ""),
    (98, "Elevacoes internas", "TEM", "PR-15", ""),
    (99, "Elevacao da cozinha", "TEM", "PR-15", ""),
    (100, "Elevacao da lavanderia", "FALTA", "", "elevacoes por ambiente"),
    (101, "Elevacao dos banheiros", "TEM", "PR-22", "PR-23"),
    (102, "Elevacao dos quartos", "FALTA", "", "=100"),
    (103, "Elevacao do closet", "FALTA", "", "=100"),
    (104, "Elevacao do home office", "FALTA", "", "=100"),
    (105, "Elevacao da area gourmet", "FALTA", "", "=100"),
    (106, "Elevacao de paineis de TV", "FALTA", "", "=100"),
    (107, "Elevacao de paredes especiais", "TEM", "PR-35", "cortina de vidro"),
    # ---- E. esquadrias
    (108, "Planta de esquadrias", "PARCIAL", "PR-02", "tags na planta; falta a prancha com cada tipo desenhado"),
    (109, "Quadro de portas", "TEM", "PR-09", ""),
    (110, "Quadro de janelas", "TEM", "PR-09", ""),
    (111, "Quadro geral de esquadrias", "TEM", "PR-09", "=109"),
    (112, "Detalhamento de portas", "FALTA", "", "elevacao e secao por familia"),
    (113, "Detalhamento de janelas", "FALTA", "", "=112"),
    (114, "Detalhamento de portas de correr", "FALTA", "", "PV02, PG01, CV01"),
    (115, "Detalhamento de esquadrias de aluminio", "FALTA", "", "=112"),
    (116, "Detalhamento de esquadrias de PVC", "NA", "ESQUADRIAS", "projeto em aluminio"),
    (117, "Detalhamento de brises", "TEM", "PR-34", "ripa, travessa e massa em fachada.brises"),
    (118, "Detalhamento de venezianas", "NA", "ESQUADRIAS", "nao ha veneziana"),
    (119, "Detalhamento de portoes", "FALTA", "", "PG01 ripado, folha, trilho e motor"),
    (120, "Detalhamento de trilhos e roldanas", "FALTA", "", "=114"),
    (121, "Detalhamento de peitoris e pingadeiras", "FALTA", "", "=112"),
    (122, "Detalhamento de soleiras", "FALTA", "", "=112"),
    (123, "Detalhamento de vedacao de esquadrias", "FALTA", "", "=112"),
    # ---- F. marcenaria
    (124, "Planta de marcenaria", "FALTA", "", "armarios e bancadas com codigo, em prancha propria"),
    (125, "Mapa de moveis planejados", "FALTA", "", "=124"),
    (126, "Detalhamento da cozinha", "FALTA", "", "elevacao em PR-15; falta o detalhamento de fabricacao"),
    (127, "Detalhamento do closet", "FALTA", "", ""),
    (128, "Detalhamento dos dormitorios", "FALTA", "", ""),
    (129, "Detalhamento de banheiros", "PARCIAL", "PR-22", "bancadas e nichos; falta o gabinete"),
    (130, "Detalhamento de lavanderia", "FALTA", "", ""),
    (131, "Detalhamento de home office", "FALTA", "", ""),
    (132, "Detalhamento de paineis de TV", "FALTA", "", ""),
    (133, "Detalhamento de nichos", "PARCIAL", "PR-22", "REV-NICHO no BOM"),
    (134, "Detalhamento de bancos", "NA", "LAYOUT", "sem banco de marcenaria no programa; o da piscina e de alvenaria (PR-34)"),
    (135, "Detalhamento de cabeceiras", "FALTA", "", ""),
    (136, "Detalhamento de roupeiros", "FALTA", "", "AR-11 a AR-13"),
    (137, "Detalhamento de armarios", "FALTA", "", "=124"),
    (138, "Detalhamento de gaveteiros", "FALTA", "", "AR-14"),
    (139, "Detalhamento de prateleiras", "FALTA", "", "AR-05, AR-09"),
    (140, "Detalhamento de bancadas", "PARCIAL", "PR-15", "granito com cuba; falta o detalhe de apoio"),
    (141, "Plano de corte de chapas de marcenaria", "FALTA", "", "nesting de MDF por movel"),
    (142, "Plano de furacao de marcenaria", "FALTA", "", "sistema 32"),
    (143, "Plano de ferragens", "FALTA", "", "dobradicas e corredicas por movel"),
    (144, "Mapa de puxadores", "FALTA", "", ""),
    (145, "Lista de pecas de marcenaria", "FALTA", "", ""),
    # ---- G. estrutura
    (146, "Planta estrutural geral", "TEM", "PR-20", "PR-18"),
    (147, "Planta de fundacoes", "TEM", "PR-37", ""),
    (148, "Planta de radier", "TEM", "PR-37", ""),
    (149, "Planta de sapatas", "NA", "PR-37", "fundacao em radier"),
    (150, "Planta de blocos", "NA", "PR-37", "=149"),
    (151, "Planta de estacas", "NA", "PR-37", "=149"),
    (152, "Planta de vigas baldrame", "NA", "PR-37", "=149"),
    (153, "Planta de pilares", "TEM", "PR-02", "PL-01 a PL-10; PR-20"),
    (154, "Planta de vigas", "TEM", "PR-20", "V-01 em diante com carga declarada"),
    (155, "Planta de lajes", "TEM", "PR-20", "entrepiso LSF"),
    (156, "Planta de formas", "PARCIAL", "PR-37", "forma de borda; falta a planta de formas do radier"),
    (157, "Planta de armacao", "PARCIAL", "PR-37", "tela Q196 dupla; falta a planta de armacao"),
    (158, "Detalhamento de fundacoes", "TEM", "PR-37", ""),
    (159, "Detalhamento de pilares", "TEM", "PR-20", "det. 3: pilar embutido em parede LSF"),
    (160, "Detalhamento de vigas", "TEM", "PR-20", ""),
    (161, "Detalhamento de lajes", "TEM", "PR-20", ""),
    (162, "Detalhamento de escadas", "TEM", "PR-25", ""),
    (163, "Detalhamento de balancos", "TEM", "PR-20", "varanda de 3 m sobre pilares"),
    (164, "Detalhamento de consoles", "NA", "PR-20", "nao ha console"),
    (165, "Detalhamento de juntas estruturais", "NA", "PR-37", "=79"),
    (166, "Detalhamento de ancoragens", "TEM", "PR-20", "nucleo/piso.ancorar"),
    (167, "Detalhamento de bases metalicas", "TEM", "PR-20", "base do pilar 200 x 200"),
    (168, "Detalhamento de chumbadores", "TEM", "PR-20", "M10 de expansao, por painel"),
    (169, "Detalhamento de ligacoes estruturais", "TEM", "PR-20", "PR-10"),
    (170, "Mapa de cargas", "TEM", "PR-40", ""),
    (171, "Memorial grafico de cargas", "TEM", "PR-40", "ENG:paineis"),
    (172, "Esquema de transferencia de cargas", "TEM", "ENG:paineis", ""),
    (173, "Planta de contencoes estruturais", "NA", "PR-47", "=40"),
    (174, "Planta de muros estruturais", "NA", "BOM", "muro de vedacao, nao estrutural"),
    # ---- H. steel frame
    (175, "Planta de modulacao do steel frame", "TEM", "PR-18", "malha de 600 em PR-02"),
    (176, "Planta de eixos estruturais", "TEM", "PR-02", "PR-31"),
    (177, "Elevacao estrutural de cada painel", "TEM", "ENG:paineis", "62 paineis"),
    (178, "Numeracao de paineis", "TEM", "PR-18", ""),
    (179, "Numeracao de montantes", "TEM", "ENG:pecas", ""),
    (180, "Numeracao de guias", "TEM", "ENG:pecas", ""),
    (181, "Desenho dos montantes", "TEM", "PR-36", ""),
    (182, "Desenho das guias", "TEM", "PR-36", ""),
    (183, "Desenho de vergas", "TEM", "PR-36", ""),
    (184, "Desenho de ombreiras", "TEM", "PR-36", ""),
    (185, "Desenho de reforcos", "TEM", "PR-36", ""),
    (186, "Detalhamento de cantos", "TEM", "PR-10", ""),
    (187, "Detalhamento de encontros em T", "FALTA", "", "detalhes de encontro"),
    (188, "Detalhamento de encontros em cruz", "FALTA", "", "=187"),
    (189, "Detalhamento de paineis duplos", "NA", "ENG:paineis", "nao ha painel duplo"),
    (190, "Planta de contraventamento", "FALTA", "", "dado em piso.contraventar; falta a planta"),
    (191, "Detalhamento de fitas de contraventamento", "FALTA", "", "=190"),
    (192, "Detalhamento de placas estruturais", "PARCIAL", "PR-12", "OSB por familia; o contraventamento e por fita"),
    (193, "Detalhamento de hold-downs", "TEM", "PR-20", "=166"),
    (194, "Detalhamento de ancoragens a fundacao", "TEM", "PR-20", "=166"),
    (195, "Detalhamento de ligacoes entre paineis", "TEM", "PR-10", ""),
    (196, "Detalhamento de parafusos", "TEM", "PR-36", ""),
    (197, "Mapa de fixadores", "TEM", "BOM", "n_parafusos por painel em ENG:paineis"),
    (198, "Desenho de trelicas", "NA", "PR-20", "cobertura plana em vigamento"),
    (199, "Desenho de vigas de piso", "TEM", "PR-20", ""),
    (200, "Desenho de joists", "TEM", "PR-20", "=199"),
    (201, "Desenho de entrepiso", "TEM", "PR-20", ""),
    (202, "Detalhe parede/fundacao", "TEM", "PR-10", ""),
    (203, "Detalhe parede/cobertura", "TEM", "PR-10", ""),
    (204, "Detalhe parede/piso", "TEM", "PR-10", ""),
    (205, "Detalhe parede externa", "TEM", "PR-10", "det. 1, 1:5"),
    (206, "Detalhe parede interna", "TEM", "PR-13", ""),
    (207, "Detalhe area molhada", "TEM", "PR-22", ""),
    (208, "Detalhe de parede com carga suspensa", "FALTA", "", "reforco onde ha TV e armario suspenso"),
    (209, "Mapa de reforcos internos", "FALTA", "", "=208"),
    (210, "Mapa de passagens de instalacoes", "TEM", "PR-21", ""),
    (211, "Mapa de furos em perfis", "TEM", "PR-21", ""),
    (212, "Mapa de protecao contra perfuracao", "TEM", "PR-21", "bucha e chapa de protecao"),
    (213, "Plano de fabricacao dos paineis", "TEM", "PR-18", "ENG:paineis"),
    (214, "Plano de montagem dos paineis", "TEM", "ENG:montagem", "69 passos com ferramenta, massa e horas"),
    (215, "Vista explodida do steel frame", "FALTA", "", "cena 3D por painel afastado"),
    (216, "Vista 3D somente da estrutura", "TEM", "3D", "camada LSF"),
    (217, "Vista por etapas de montagem", "TEM", "ENG:montagem", "=214"),
    (218, "Lista de corte dos perfis", "TEM", "ENG:corte", ""),
    (219, "Lista de pecas", "TEM", "ENG:pecas", ""),
    (220, "Lista de perfis", "TEM", "PR-36", ""),
    (221, "Lista de conectores", "TEM", "BOM", ""),
    (222, "Lista de parafusos", "TEM", "BOM", ""),
    (223, "Plano de etiquetagem", "PARCIAL", "ENG:pecas", "codigo unico por peca; falta a etiqueta fisica"),
    (224, "Plano de embalagem", "TEM", "ENG:documentos", "packing list por viagem (R69)"),
    (225, "Plano de transporte", "TEM", "ENG:logistica", "carreta aberta, paineis em pe (R69)"),
    (226, "Plano de carga em caminhao", "TEM", "ENG:logistica", "=225"),
    (227, "Tabela de tolerancias de fabricacao", "PARCIAL", "ENG:documentos", "tolerancia por peca no relatorio de inspecao; falta a tabela geral"),
    (228, "Tabela de tolerancias de montagem", "FALTA", "", ""),
    # ---- I. eletrica
    (229, "Planta eletrica geral", "TEM", "PR-27", ""),
    (230, "Planta de tomadas", "TEM", "PR-27", ""),
    (231, "Planta de tomadas especificas", "TEM", "PR-27", "TUE"),
    (232, "Planta de interruptores", "TEM", "PR-27", ""),
    (233, "Planta de iluminacao", "TEM", "PR-16", "PR-27"),
    (234, "Planta de iluminacao externa", "PARCIAL", "PR-36", "ILUMINACAO_FACHADA sem coordenada; falta o desenho"),
    (235, "Planta de iluminacao de emergencia", "NA", "PR-27", "residencia unifamiliar: nao exigida"),
    (236, "Planta de quadros eletricos", "TEM", "PR-27", "TC-05 e TC-06"),
    (237, "Diagrama unifilar", "FALTA", "", "quadro de cargas em PR-40; falta o unifilar"),
    (238, "Diagrama multifilar", "NA", "PR-40", "unifamiliar: o unifilar basta"),
    (239, "Quadro de cargas", "TEM", "PR-40", ""),
    (240, "Mapa de circuitos", "FALTA", "", "=237"),
    (241, "Planta de aterramento", "TEM", "PR-41", "anel no radier"),
    (242, "Planta de equipotencializacao", "TEM", "PR-41", "BEP"),
    (243, "Planta de SPDA", "TEM", "PR-41", ""),
    (244, "Detalhamento de quadros eletricos", "FALTA", "", "=237"),
    (245, "Planta de alimentacao de equipamentos", "TEM", "PR-27", "TUE"),
    (246, "Planta de carregador de veiculo eletrico", "TEM", "PR-27", "TUE-VE 7,4 kW"),
    (247, "Planta de nobreak", "NA", "PR-40", "nao previsto"),
    (248, "Planta de baterias", "NA", "PR-41", "FV sem armazenamento"),
    (249, "Planta de gerador", "NA", "PR-40", "nao previsto"),
    # ---- J. energia solar
    (250, "Planta fotovoltaica", "TEM", "PR-41", ""),
    (251, "Layout de paineis solares", "TEM", "PR-41", ""),
    (252, "Diagrama eletrico do sistema fotovoltaico", "FALTA", "", "strings, inversor, protecoes"),
    (253, "Detalhamento de inversores", "PARCIAL", "PR-41", "TC-17 locado; falta o detalhe"),
    (254, "Detalhamento de baterias", "NA", "PR-41", "=248"),
    (255, "Planta de passagem de cabos solares", "FALTA", "", "=252"),
    (256, "Detalhamento de estrutura de fixacao", "PARCIAL", "BOM", "estrutura no BOM; falta o detalhe"),
    # ---- K. hidraulica
    (257, "Planta de agua fria", "TEM", "PR-26", ""),
    (258, "Planta de agua quente", "NA", "DOC:DECISOES", "chuveiros eletricos: sem rede de agua quente"),
    (259, "Planta de agua potavel", "TEM", "PR-26", "=257"),
    (260, "Planta de agua nao potavel", "NA", "PR-38", "sem reuso, decidido"),
    (261, "Planta de reservatorios", "TEM", "PR-26", "cisterna TC-01 e caixa"),
    (262, "Planta de caixa d'agua", "TEM", "PR-26", "=261"),
    (263, "Planta de recalque", "TEM", "PR-26", "TC-02"),
    (264, "Planta de bombas", "TEM", "PR-26", "=263"),
    (265, "Planta de pressurizacao", "NA", "PR-26", "caixa elevada: gravidade"),
    (266, "Diagrama vertical hidraulico", "FALTA", "", "prumadas no modelo; falta o diagrama"),
    (267, "Isometrico de agua fria", "FALTA", "", ""),
    (268, "Isometrico de agua quente", "NA", "DOC:DECISOES", "=258"),
    (269, "Detalhamento de registros", "FALTA", "", "=266"),
    (270, "Detalhamento de barriletes", "FALTA", "", "=266"),
    (271, "Detalhamento de shafts hidraulicos", "TEM", "PR-21", ""),
    # ---- L. esgoto
    (272, "Planta sanitaria", "TEM", "PR-26", ""),
    (273, "Planta de esgoto", "TEM", "PR-26", "=272"),
    (274, "Planta de ventilacao sanitaria", "FALTA", "", ""),
    (275, "Diagrama vertical de esgoto", "FALTA", "", ""),
    (276, "Isometrico de esgoto", "FALTA", "", ""),
    (277, "Isometrico de ventilacao", "FALTA", "", "=274"),
    (278, "Planta de caixas sifonadas", "TEM", "PR-26", "RALOS"),
    (279, "Planta de caixas de inspecao", "FALTA", "", ""),
    (280, "Detalhamento de caixas de gordura", "FALTA", "", ""),
    (281, "Detalhamento de fossas", "NA", "PR-26", "rede publica assumida (H)"),
    (282, "Detalhamento de conexoes sanitarias", "FALTA", "", "=276"),
    # ---- M. pluvial
    (283, "Planta pluvial", "TEM", "PR-29", ""),
    (284, "Planta de drenagem do terreno", "TEM", "PR-38", ""),
    (285, "Planta de drenagem de cobertura", "TEM", "PR-05", "PR-29"),
    (286, "Planta de calhas", "TEM", "PR-05", "PR-10"),
    (287, "Planta de condutores verticais", "TEM", "PR-29", ""),
    (288, "Planta de caixas pluviais", "TEM", "PR-29", ""),
    (289, "Planta de retencao pluvial", "TEM", "PR-38", ""),
    (290, "Planta de infiltracao", "PARCIAL", "PR-38", "superficies permeaveis; sem trincheira de infiltracao"),
    (291, "Planta de reservatorio de chuva", "TEM", "PR-38", "TC-03"),
    (292, "Planta de reuso de agua pluvial", "NA", "PR-38", "=260"),
    (293, "Detalhamento de drenos", "TEM", "PR-29", ""),
    (294, "Isometrico de aguas pluviais", "FALTA", "", ""),
    # ---- N. gas
    (295, "Planta de gas", "FALTA", "", "rede do abrigo ao cooktop e a churrasqueira"),
    (296, "Planta de abrigo de gas", "PARCIAL", "PR-28", "TC-04 locado; falta o detalhe do abrigo"),
    (297, "Isometrico de gas", "FALTA", "", "=295"),
    (298, "Detalhamento de registros de gas", "FALTA", "", "=295"),
    (299, "Detalhamento de tubulacoes de gas", "FALTA", "", "=295"),
    (300, "Detalhamento de ventilacao do abrigo", "FALTA", "", "=296"),
    # ---- O. climatizacao
    (301, "Planta de climatizacao", "TEM", "PR-28", ""),
    (302, "Planta de ar-condicionado", "TEM", "PR-28", "=301"),
    (303, "Planta de evaporadoras", "TEM", "PR-28", ""),
    (304, "Planta de condensadoras", "TEM", "PR-28", "nichos TC"),
    (305, "Planta de tubulacoes frigorigenas", "TEM", "PR-28", ""),
    (306, "Planta de drenos de ar-condicionado", "TEM", "PR-28", ""),
    (307, "Planta de alimentacao eletrica de climatizacao", "TEM", "PR-27", ""),
    (308, "Planta de ventilacao", "TEM", "PR-16", "ventiladores"),
    (309, "Planta de exaustao", "TEM", "PR-28", ""),
    (310, "Planta de coifas", "TEM", "PR-28", ""),
    (311, "Planta de dutos", "TEM", "PR-28", ""),
    (312, "Planta de renovacao de ar", "FALTA", "", "vazao por ambiente climatizado"),
    (313, "Isometrico de climatizacao", "FALTA", "", ""),
    (314, "Detalhamento de suportes", "FALTA", "", "condensadora e linha"),
    (315, "Detalhamento de area tecnica de condensadoras", "TEM", "PR-28", "PR-10 det. 4"),
    # ---- P. dados e automacao
    (316, "Planta de internet", "FALTA", "", "rede de dados com rack, pontos e Wi-Fi"),
    (317, "Planta de rede estruturada", "FALTA", "", "=316"),
    (318, "Planta de Wi-Fi", "FALTA", "", "=316"),
    (319, "Planta de pontos de dados", "TEM", "PR-27", ""),
    (320, "Planta de TV", "PARCIAL", "PR-27", "pontos de TV com os de dados"),
    (321, "Planta de telefonia", "NA", "PR-27", "telefonia por IP na rede de dados"),
    (322, "Planta de interfone", "FALTA", "", "=329"),
    (323, "Planta de automacao residencial", "FALTA", "", "cenas, sensores e comandos"),
    (324, "Planta de sensores", "FALTA", "", "=323"),
    (325, "Planta de cortinas automatizadas", "FALTA", "", "=323"),
    (326, "Planta de comandos inteligentes", "FALTA", "", "=323"),
    (327, "Diagrama de automacao", "FALTA", "", "=323"),
    (328, "Planta de rack de telecomunicacoes", "FALTA", "", "=316"),
    # ---- Q. seguranca eletronica
    (329, "Planta de CFTV", "FALTA", "", "cameras, alarme e acesso"),
    (330, "Planta de cameras", "FALTA", "", "=329"),
    (331, "Planta de alarme", "FALTA", "", "=329"),
    (332, "Planta de sensores de presenca", "FALTA", "", "=329"),
    (333, "Planta de sensores de abertura", "FALTA", "", "=329"),
    (334, "Planta de controle de acesso", "FALTA", "", "=329"),
    (335, "Planta de fechaduras eletronicas", "FALTA", "", "=329"),
    (336, "Planta de video porteiro", "FALTA", "", "=329"),
    (337, "Planta de sirenes", "FALTA", "", "=329"),
    (338, "Diagrama de seguranca eletronica", "FALTA", "", "=329"),
    # ---- R. incendio
    (339, "Planta de prevencao contra incendio", "FALTA", "", "extintores e sinalizacao"),
    (340, "Planta de extintores", "FALTA", "", "=339"),
    (341, "Planta de sinalizacao de emergencia", "FALTA", "", "=339"),
    (342, "Planta de iluminacao de emergencia", "NA", "PR-27", "=235"),
    (343, "Planta de rotas de fuga", "NA", "PR-17", "unifamiliar de dois pavimentos: nao exigida"),
    (344, "Planta de hidrantes", "NA", "PR-26", "nao exigido"),
    (345, "Planta de sprinklers", "NA", "PR-26", "nao exigido"),
    (346, "Detalhamento de equipamentos de combate", "FALTA", "", "=339"),
    # ---- S. piscina
    (347, "Planta da piscina", "TEM", "PR-34", ""),
    (348, "Planta estrutural da piscina", "PARCIAL", "PR-34", "sistema declarado; falta a estrutura"),
    (349, "Corte longitudinal da piscina", "TEM", "PR-34", "PR-10 det. 3"),
    (350, "Corte transversal da piscina", "FALTA", "", ""),
    (351, "Detalhamento de prainha", "PARCIAL", "PR-34", "PISCINA.prainha_w; falta o detalhe"),
    (352, "Detalhamento de escada da piscina", "FALTA", "", ""),
    (353, "Detalhamento de banco submerso", "PARCIAL", "PR-34", "PISCINA.banco; falta o detalhe"),
    (354, "Planta hidraulica da piscina", "PARCIAL", "PR-34", "PISCINA_SISTEMA"),
    (355, "Planta de succao", "PARCIAL", "PR-34", "=354"),
    (356, "Planta de retorno", "PARCIAL", "PR-34", "=354"),
    (357, "Planta de drenos da piscina", "PARCIAL", "PR-34", "=354"),
    (358, "Planta de skimmer", "PARCIAL", "PR-34", "=354"),
    (359, "Planta de casa de maquinas", "TEM", "PR-34", "TC na faixa tecnica"),
    (360, "Diagrama hidraulico da piscina", "FALTA", "", "=354"),
    (361, "Detalhamento de impermeabilizacao da piscina", "PARCIAL", "PR-34", ""),
    (362, "Detalhamento de bordas", "FALTA", "", ""),
    (363, "Detalhamento de iluminacao da piscina", "FALTA", "", ""),
    # ---- T. externas
    (364, "Planta de paisagismo", "TEM", "PR-32", ""),
    (365, "Planta de vegetacao", "TEM", "PR-32", "=364"),
    (366, "Planta de irrigacao", "TEM", "PR-32", ""),
    (367, "Planta de pisos externos", "TEM", "PR-38", "superficies"),
    (368, "Planta de decks", "TEM", "PR-34", ""),
    (369, "Planta de calcadas", "PARCIAL", "PR-01", "calcada publica nao desenhada"),
    (370, "Planta de acessos", "TEM", "PR-17", "PR-47"),
    (371, "Planta de rampas", "TEM", "PR-47", ""),
    (372, "Planta de muros", "PARCIAL", "PR-01", "muro no BOM e na cena; falta a elevacao"),
    (373, "Planta de cercas", "NA", "BOM", "fechamento em muro"),
    (374, "Planta de portoes", "PARCIAL", "PR-34", "=119"),
    (375, "Planta de iluminacao externa", "PARCIAL", "PR-36", "=234"),
    (376, "Planta de drenagem externa", "TEM", "PR-29", ""),
    (377, "Detalhamento de pergolados", "NA", "LAYOUT", "nao ha pergolado"),
    (378, "Detalhamento de decks", "PARCIAL", "PR-34", "WPC no BOM; falta o detalhe de apoio"),
    (379, "Detalhamento de areas gourmet externas", "TEM", "PR-35", "PR-34"),
    # ---- U. fachadas
    (380, "Planta de paginacao de fachada", "FALTA", "", "placas 1.200 x 2.400 com junta seca"),
    (381, "Elevacao de fachada revestida", "PARCIAL", "PR-07", "dois tratamentos; falta a paginacao"),
    (382, "Detalhamento de fachada ventilada", "NA", "FACHADA_MATERIAIS", "fachada aderida"),
    (383, "Detalhamento de ACM", "NA", "FACHADA_MATERIAIS", "sem ACM"),
    (384, "Detalhamento de WPC", "PARCIAL", "PR-34", "deck; falta o detalhe"),
    (385, "Detalhamento de porcelanato de fachada", "NA", "FACHADA_MATERIAIS", "sem porcelanato"),
    (386, "Detalhamento de paineis cimenticios", "TEM", "PR-13", "PR-10 det. 1"),
    (387, "Detalhamento de aluminio", "PARCIAL", "PR-34", "brises; falta fascia e caixilho"),
    (388, "Detalhamento de brises", "TEM", "PR-34", "=117"),
    (389, "Detalhamento de juntas de fachada", "FALTA", "", "=380"),
    (390, "Detalhamento de fixacoes de fachada", "FALTA", "", "=380"),
    # ---- V. impermeabilizacao
    (391, "Planta de impermeabilizacao", "PARCIAL", "PR-22", "=77"),
    (392, "Corte de impermeabilizacao", "FALTA", "", "=77"),
    (393, "Detalhamento de areas molhadas", "TEM", "PR-22", "PR-23"),
    (394, "Detalhamento de lajes", "TEM", "PR-20", ""),
    (395, "Detalhamento de coberturas", "TEM", "PR-05", "PR-10"),
    (396, "Detalhamento de ralos", "TEM", "PR-29", ""),
    (397, "Detalhamento de rodapes impermeaveis", "FALTA", "", "=77"),
    (398, "Detalhamento de encontros parede/piso", "TEM", "PR-10", ""),
    (399, "Detalhamento de juntas", "FALTA", "", "=78"),
    (400, "Detalhamento de estanqueidade ao ar", "FALTA", "", "=80"),
    (401, "Detalhamento de estanqueidade a agua", "FALTA", "", "=80"),
    # ---- W. conforto
    (402, "Mapa de isolamento termico", "TEM", "PR-12", "PR-11"),
    (403, "Mapa de isolamento acustico", "TEM", "PR-12", "PR-39"),
    (404, "Detalhamento acustico de paredes", "TEM", "PR-13", ""),
    (405, "Detalhamento acustico de pisos", "PARCIAL", "PR-20", "entrepiso; falta o detalhe acustico"),
    (406, "Detalhamento acustico de tetos", "PARCIAL", "PR-16", "forros absorventes"),
    (407, "Mapa de pontes termicas", "TEM", "PR-11", ""),
    (408, "Detalhamento de correcao de pontes termicas", "PARCIAL", "PR-11", "fracao de montante; falta o detalhe"),
    (409, "Estudo de desempenho de fachada", "TEM", "PR-11", "PR-41"),
    (410, "Estudo de desempenho termico da cobertura", "TEM", "PR-11", ""),
    # ---- X. detalhes
    (411, "Detalhe de rodape", "FALTA", "", "detalhes complementares"),
    (412, "Detalhe de soleira", "FALTA", "", "=411"),
    (413, "Detalhe de peitoril", "FALTA", "", "=411"),
    (414, "Detalhe de pingadeira", "FALTA", "", "=411"),
    (415, "Detalhe de encontro de paredes", "TEM", "PR-10", ""),
    (416, "Detalhe parede/piso", "TEM", "PR-10", ""),
    (417, "Detalhe parede/teto", "TEM", "PR-20", "det. 2: junta de deslizamento"),
    (418, "Detalhe parede/cobertura", "TEM", "PR-10", ""),
    (419, "Detalhe de cobertura", "TEM", "PR-10", ""),
    (420, "Detalhe de calha", "TEM", "PR-10", ""),
    (421, "Detalhe de rufo", "TEM", "PR-10", "fascia com rufo integrado (R67)"),
    (422, "Detalhe de cumeeira", "NA", "PR-05", "cobertura plana"),
    (423, "Detalhe de beiral", "NA", "PR-05", "platibanda"),
    (424, "Detalhe de shaft", "TEM", "PR-21", ""),
    (425, "Detalhe de alcapao", "FALTA", "", "=411"),
    (426, "Detalhe de passagem de instalacoes", "TEM", "PR-21", ""),
    (427, "Detalhe de nichos", "PARCIAL", "PR-22", "=133"),
    (428, "Detalhe de bancadas", "PARCIAL", "PR-15", "=140"),
    (429, "Detalhe de escadas", "TEM", "PR-25", ""),
    (430, "Detalhe de guarda-corpos", "FALTA", "", "=411"),
    (431, "Detalhe de corrimaos", "FALTA", "", "=411"),
    # ---- Y. fabricacao
    (432, "Desenho para fabricacao", "TEM", "ENG:pecas", "PR-36"),
    (433, "Desenho para fabricacao na China", "NA", "PR-40", "fabricacao com praca local, decisao de mercado"),
    (434, "Desenho de peca individual", "TEM", "ENG:pecas", ""),
    (435, "Desenho de subconjunto", "TEM", "ENG:paineis", ""),
    (436, "Desenho de conjunto", "TEM", "PR-18", ""),
    (437, "Desenho de montagem", "TEM", "PR-18", ""),
    (438, "Desenho de furacao", "TEM", "PR-21", ""),
    (439, "Desenho de rasgos", "NA", "PR-36", "perfis sem rasgo"),
    (440, "Desenho de dobras", "NA", "PR-36", "perfis comprados conformados"),
    (441, "Desenho de soldagem", "NA", "PR-36", "estrutura parafusada"),
    (442, "Desenho de usinagem", "NA", "PR-36", "corte e furo, sem usinagem"),
    (443, "Plano de corte", "TEM", "ENG:corte", ""),
    (444, "Plano de corte de chapas", "TEM", "ENG:corte", "placas de vedacao"),
    (445, "Plano de corte de perfis", "TEM", "ENG:corte", ""),
    (446, "Plano de nesting", "TEM", "ENG:corte", ""),
    (447, "Nesting de chapas", "TEM", "ENG:corte", "=444"),
    (448, "Nesting de perfis", "TEM", "ENG:corte", "=445"),
    (449, "Lista de materiais", "TEM", "BOM", ""),
    (450, "Lista de pecas", "TEM", "ENG:pecas", "=219"),
    (451, "Lista de ferragens", "TEM", "BOM", ""),
    (452, "Lista de fixadores", "TEM", "BOM", "=222"),
    (453, "Lista de conectores", "TEM", "BOM", "=221"),
    (454, "Lista de embalagens", "TEM", "ENG:documentos", "=224"),
    (455, "Lista de volumes", "TEM", "ENG:documentos", "=224"),
    (456, "Plano de etiquetagem", "PARCIAL", "ENG:pecas", "=223"),
    (457, "Plano de rastreabilidade", "PARCIAL", "ENG:pecas", "=223"),
    (458, "Plano de pre-montagem", "PARCIAL", "PR-18", "paineis saem montados; falta o plano"),
    (459, "Plano de embalagem", "TEM", "ENG:documentos", "=224"),
    (460, "Plano de carga", "TEM", "ENG:logistica", "=225"),
    (461, "Plano de transporte", "TEM", "ENG:logistica", "=225"),
    (462, "Plano de descarga", "FALTA", "", "=225"),
    (463, "Plano de montagem em obra", "TEM", "ENG:montagem", "=214"),
    (464, "Sequencia grafica de montagem", "TEM", "ENG:montagem", "=214"),
    (465, "Manual grafico de montagem", "TEM", "ENG:documentos", "manual de montagem gerado"),
    (466, "Mapa de tolerancias", "FALTA", "", "=227"),
    (467, "Mapa de controle dimensional", "TEM", "ENG:documentos", "relatorio de inspecao dimensional por peca"),
    (468, "Mapa de inspecao de fabricacao", "PARCIAL", "ENG:documentos", "inspecao dimensional; falta a inspecao de solda e fixacao"),
    # ---- Z. compatibilizacao
    (469, "Planta de compatibilizacao geral", "TEM", "PR-14", "modelo de fonte unica: nao ha o que compatibilizar, ha o que auditar"),
    (470, "Arquitetura + estrutura", "TEM", "PR-20", "=469"),
    (471, "Arquitetura + eletrica", "TEM", "PR-27", "=469"),
    (472, "Arquitetura + hidraulica", "TEM", "PR-26", "=469"),
    (473, "Arquitetura + climatizacao", "TEM", "PR-28", "=469"),
    (474, "Estrutura + eletrica", "TEM", "PR-21", "=469"),
    (475, "Estrutura + hidraulica", "TEM", "PR-21", "=469"),
    (476, "Estrutura + climatizacao", "TEM", "PR-21", "=469"),
    (477, "Steel frame + eletrica", "TEM", "PR-21", "=469"),
    (478, "Steel frame + hidraulica", "TEM", "PR-21", "=469"),
    (479, "Steel frame + climatizacao", "TEM", "PR-21", "=469"),
    (480, "Steel frame + marcenaria", "FALTA", "", "reforco onde armario e suspenso: =208"),
    (481, "Planta de interferencias", "TEM", "PR-21", "auditoria de colisoes"),
    (482, "Mapa de conflitos", "TEM", "PR-14", ""),
    (483, "Vista 3D de interferencias", "FALTA", "", "cena com as penetracoes"),
    (484, "Relatorio grafico de clashes", "TEM", "PR-14", ""),
    # ---- AA. BIM
    (485, "Modelo BIM arquitetonico", "PARCIAL", "OUT:modelo3d.json", "modelo parametrico proprio; falta IFC"),
    (486, "Modelo BIM estrutural", "PARCIAL", "OUT:engenharia.json", "=485"),
    (487, "Modelo BIM eletrico", "PARCIAL", "PR-27", "=485"),
    (488, "Modelo BIM hidraulico", "PARCIAL", "PR-26", "=485"),
    (489, "Modelo BIM sanitario", "PARCIAL", "PR-26", "=485"),
    (490, "Modelo BIM de climatizacao", "PARCIAL", "PR-28", "=485"),
    (491, "Modelo BIM de steel frame", "PARCIAL", "OUT:engenharia.json", "=485"),
    (492, "Modelo BIM federado", "PARCIAL", "OUT:modelo3d.json", "=485"),
    (493, "Modelo BIM de compatibilizacao", "TEM", "PR-14", "=469"),
    (494, "Modelo BIM 4D", "PARCIAL", "PR-40", "fases; falta a sequencia por peca"),
    (495, "Modelo BIM 5D", "TEM", "BOM", "quantidade e custo do mesmo modelo"),
    (496, "Modelo BIM 6D", "NA", "BOM", "sustentabilidade nao modelada alem do termico"),
    (497, "Modelo BIM para manutencao", "FALTA", "", "=592"),
    (498, "Modelo BIM as-built", "EXTERNO", "obra", "so depois da obra"),
    (499, "Extracao de quantitativos do modelo", "TEM", "BOM", ""),
    (500, "Extracao automatica de pecas e componentes", "TEM", "ENG:pecas", ""),
    # ---- AB. apresentacao
    (501, "Perspectiva 3D externa", "TEM", "PR-43", ""),
    (502, "Perspectiva 3D interna", "TEM", "PR-44", "PR-45, PR-46"),
    (503, "Vista isometrica", "TEM", "PR-08", ""),
    (504, "Axonometria", "TEM", "PR-08", ""),
    (505, "Vista explodida", "FALTA", "", "=215"),
    (506, "Vista estrutural", "TEM", "3D", "camada LSF"),
    (507, "Vista das instalacoes", "PARCIAL", "3D", "tecnicos e luz; sem tubulacao na cena"),
    (508, "Vista por sistemas", "TEM", "3D", "camadas"),
    (509, "Vista por pavimentos", "TEM", "3D", "camadas terreo e superior"),
    (510, "Vista por etapas construtivas", "FALTA", "", "=214"),
    (511, "Render externo", "TEM", "OUT:render-chegada.png", "Blender, render_blender.py"),
    (512, "Render interno", "TEM", "OUT:render-T-SOC.png", ""),
    (513, "Render noturno", "FALTA", "", "com a iluminacao da PR-16"),
    (514, "Render aereo", "TEM", "OUT:render-aer-225.png", ""),
    (515, "Render da area gourmet", "FALTA", "", "cameras ja existem em perspectivas.json"),
    (516, "Render da piscina", "TEM", "OUT:render-T-DKP.png", ""),
    (517, "Render da cozinha", "FALTA", "", "=515"),
    (518, "Render dos quartos", "FALTA", "", "=515"),
    (519, "Render dos banheiros", "FALTA", "", "=515"),
    (520, "Maquete eletronica", "TEM", "3D", ""),
    (521, "Passeio virtual", "PARCIAL", "3D", "orbita e corte; sem caminhar"),
    (522, "Tour 360", "EXTERNO", "", "exige renderizador panoramico"),
    (523, "Animacao 3D", "EXTERNO", "OUT:porto-real.obj", "estudio de visualizacao; geometria, cameras (perspectivas.json) e sequencia (ENG:montagem) saem do modelo"),
    (524, "Video de montagem", "EXTERNO", "OUT:porto-real.obj", "estudio de visualizacao; geometria, cameras (perspectivas.json) e sequencia (ENG:montagem) saem do modelo"),
    (525, "Video de fases da obra", "EXTERNO", "OUT:porto-real.obj", "estudio de visualizacao; geometria, cameras (perspectivas.json) e sequencia (ENG:montagem) saem do modelo"),
    # ---- AC. obra
    (526, "Prancha geral de execucao", "TEM", "PR-02", "o caderno"),
    (527, "Prancha de locacao", "TEM", "PR-31", ""),
    (528, "Prancha de eixos", "TEM", "PR-31", ""),
    (529, "Prancha de niveis", "TEM", "PR-47", "PR-06"),
    (530, "Prancha de detalhes executivos", "TEM", "PR-10", ""),
    (531, "Prancha de montagem", "TEM", "ENG:montagem", "=214"),
    (532, "Planta do canteiro", "FALTA", "", "canteiro no recuo de frente e na faixa tecnica"),
    (533, "Planta de logistica da obra", "FALTA", "", "=532"),
    (534, "Planta de armazenamento de materiais", "FALTA", "", "=532"),
    (535, "Planta de circulacao de trabalhadores", "FALTA", "", "=532"),
    (536, "Planta de acesso de veiculos", "FALTA", "", "=532"),
    (537, "Plano de icamento", "TEM", "ENG:logistica", "pontos de icamento e tracao no cabo por painel"),
    (538, "Plano de escoramento", "NA", "PR-18", "paineis autoportantes"),
    (539, "Plano de sequenciamento da obra", "PARCIAL", "PR-40", "fases; falta o sequenciamento por painel"),
    (540, "Plano de faseamento", "TEM", "PR-40", ""),
    (541, "Mapa de inspecoes", "FALTA", "", "plano de qualidade"),
    (542, "Checklist grafico de execucao", "FALTA", "", "=541"),
    (543, "Mapa de pontos criticos", "FALTA", "", "=541"),
    (544, "Mapa de seguranca de obra", "FALTA", "", "=532"),
    # ---- AD. orcamento
    (545, "Desenho para levantamento quantitativo", "TEM", "BOM", "o modelo e o levantamento"),
    (546, "Mapa de areas", "TEM", "PR-09", ""),
    (547, "Mapa de volumes", "TEM", "BOM", ""),
    (548, "Mapa de materiais", "TEM", "PR-30", "=71"),
    (549, "Quantitativo grafico de estrutura", "TEM", "ENG:pecas", ""),
    (550, "Quantitativo grafico de revestimentos", "TEM", "PR-30", ""),
    (551, "Quantitativo de steel frame", "TEM", "ENG:pecas", ""),
    (552, "Quantitativo de marcenaria", "TEM", "BOM", ""),
    (553, "Quantitativo de instalacoes", "TEM", "BOM", ""),
    (554, "Mapa de compras", "TEM", "PR-40", ""),
    (555, "Prancha para cotacao de fornecedores", "TEM", "OUT:PORTO_REAL_COTACAO.xlsx", ""),
    (556, "Prancha para fabricacao por fornecedor", "PARCIAL", "PR-40", "familias por fornecedor; falta a prancha por fornecedor"),
    (557, "Prancha para importacao", "NA", "PR-40", "=433"),
    (558, "Mapa de lotes de compra", "FALTA", "", "por fase"),
    (559, "Mapa de embalagem por modulo", "FALTA", "", "=224"),
    (560, "Mapa de logistica de importacao", "NA", "PR-40", "=433"),
    # ---- AE. qualidade
    (561, "Plano grafico de qualidade", "FALTA", "", "ensaios ja declarados: densidade, SPDA, estanqueidade"),
    (562, "Mapa de inspecao", "FALTA", "", "=561"),
    (563, "Mapa de testes", "FALTA", "", "=561"),
    (564, "Mapa de estanqueidade", "FALTA", "", "=561"),
    (565, "Mapa de testes eletricos", "FALTA", "", "=561"),
    (566, "Mapa de testes hidraulicos", "FALTA", "", "=561"),
    (567, "Mapa de testes de esgoto", "FALTA", "", "=561"),
    (568, "Mapa de testes de climatizacao", "FALTA", "", "=561"),
    (569, "Mapa de inspecao do steel frame", "FALTA", "", "=561"),
    (570, "Mapa de torque de fixadores", "FALTA", "", "=561"),
    (571, "Mapa de controle dimensional", "TEM", "ENG:documentos", "=467"),
    (572, "Mapa de nao conformidades", "EXTERNO", "obra", "so existe com obra"),
    (573, "Mapa de correcoes", "EXTERNO", "obra", "=572"),
    (574, "Mapa de entrega tecnica", "FALTA", "", "=561"),
    # ---- AF. as-built
    (575, "Planta as-built arquitetonica", "EXTERNO", "obra", "so depois da obra"),
    (576, "Planta as-built estrutural", "EXTERNO", "obra", "=575"),
    (577, "Planta as-built eletrica", "EXTERNO", "obra", "=575"),
    (578, "Planta as-built hidraulica", "EXTERNO", "obra", "=575"),
    (579, "Planta as-built sanitaria", "EXTERNO", "obra", "=575"),
    (580, "Planta as-built de climatizacao", "EXTERNO", "obra", "=575"),
    (581, "Planta as-built de dados", "EXTERNO", "obra", "=575"),
    (582, "Planta as-built de seguranca", "EXTERNO", "obra", "=575"),
    (583, "Planta as-built de piscina", "EXTERNO", "obra", "=575"),
    (584, "Planta as-built de steel frame", "EXTERNO", "obra", "=575"),
    (585, "Mapa de tubulacoes ocultas", "FALTA", "", "as tubulacoes de projeto, por parede"),
    (586, "Mapa de cabos ocultos", "FALTA", "", "=585"),
    (587, "Mapa de registros", "FALTA", "", "=266"),
    (588, "Mapa de valvulas", "FALTA", "", "=266"),
    (589, "Mapa de quadros", "TEM", "PR-27", ""),
    (590, "Mapa de equipamentos", "TEM", "PR-36", "TECNICOS e EQUIPAMENTOS"),
    (591, "Mapa de pontos de manutencao", "FALTA", "", "=592"),
    (592, "Manual grafico de manutencao", "FALTA", "", "NBR 14037: por sistema, com periodicidade"),
    (593, "Plano de manutencao preventiva", "FALTA", "", "NBR 5674: =592"),
    (594, "Mapa de substituicao de componentes", "FALTA", "", "VUP por sistema (NBR 15575): =592"),
    (595, "Registro grafico de reformas futuras", "EXTERNO", "obra", ""),
    # ---- AG. documentacao
    (596, "Indice geral de pranchas", "TEM", "PR-33", ""),
    (597, "Codificacao de desenhos", "TEM", "PR-33", "PR-nn"),
    (598, "Codificacao de ambientes", "TEM", "PR-02", "T-xxx e S-xxx"),
    (599, "Codificacao de materiais", "TEM", "PR-36", "SKU do BOM"),
    (600, "Codificacao de equipamentos", "TEM", "PR-36", "TC-, EQ-"),
    (601, "Codificacao de pecas", "TEM", "ENG:pecas", ""),
    (602, "Legenda geral", "PARCIAL", "PR-33", "legendas por prancha; falta a geral"),
    (603, "Quadro de revisoes", "TEM", "PR-33", "REVISOES"),
    (604, "Quadro de notas gerais", "TEM", "PR-33", "notas por prancha"),
    (605, "Quadro de especificacoes", "TEM", "PR-13", ""),
    (606, "Quadro de materiais", "TEM", "PR-30", ""),
    (607, "Quadro de acabamentos", "TEM", "PR-30", ""),
    (608, "Quadro de quantitativos", "TEM", "BOM", ""),
    (609, "Quadro de esquadrias", "TEM", "PR-09", ""),
    (610, "Quadro de equipamentos", "TEM", "PR-36", ""),
    (611, "Matriz de disciplinas", "FALTA", "", "disciplina x prancha"),
    (612, "Matriz de compatibilizacao", "TEM", "PR-14", "=469"),
    (613, "Matriz de interfaces", "FALTA", "", "=611"),
    (614, "Matriz de responsabilidades", "FALTA", "", "quem assina o que (ART/RRT)"),
    (615, "Caderno de detalhes", "TEM", "PR-10", "PR-20, PR-21, PR-25"),
    (616, "Caderno de fabricacao", "TEM", "ENG:pecas", "PR-18, PR-36"),
    (617, "Caderno de montagem", "TEM", "ENG:documentos", "=465"),
    (618, "Caderno de compatibilizacao", "TEM", "PR-14", ""),
    (619, "Caderno de especificacoes", "TEM", "PR-13", ""),
    (620, "Caderno as-built", "EXTERNO", "obra", "=575"),
    (621, "Prancha mestre do projeto", "TEM", "PR-48", "esta matriz"),
]

STATUS = ("TEM", "PARCIAL", "FALTA", "EXTERNO", "NA")


def bloco_de(n: int) -> tuple:
    for letra, a, b, nome in BLOCOS:
        if a <= n <= b:
            return letra, nome
    raise KeyError(n)


def itens() -> list[dict]:
    out = []
    for n, nome, status, ref, nota in ITENS:
        letra, bloco = bloco_de(n)
        sin = None
        if nota.startswith("="):
            try:
                sin = int(nota[1:].split(":")[0].split(" ")[0])
            except ValueError:
                sin = None
        out.append(dict(n=n, nome=nome, status=status, ref=ref, nota=nota,
                        bloco=letra, bloco_nome=bloco, sinonimo_de=sin))
    return out


def distintos() -> list[dict]:
    """Entregaveis distintos: cada sinonimo conta uma vez, no item que o resolve."""
    return [i for i in itens() if i["sinonimo_de"] is None]


def resumo() -> dict:
    todos = itens()
    dist = distintos()
    por_status = {s: sum(1 for i in dist if i["status"] == s) for s in STATUS}
    por_bloco = {}
    for letra, a, b, nome in BLOCOS:
        bi = [i for i in dist if i["bloco"] == letra]
        por_bloco[letra] = dict(nome=nome, n=len(bi),
                                **{s: sum(1 for i in bi if i["status"] == s) for s in STATUS})
    return dict(linhas=len(todos), distintos=len(dist), por_status=por_status,
                por_bloco=por_bloco,
                cobertura=(por_status["TEM"] + por_status["NA"]) / max(1, len(dist)),
                backlog=[i for i in dist if i["status"] == "FALTA"])


def conferir(pj, caderno_nums: set, eng_vistas: set, out_dir: str) -> list[tuple]:
    """Toda referencia existe? Toda linha tem status valido? Todo NA tem razao?"""
    import os
    falhas = []
    ns = [n for n, *_ in ITENS]
    if ns != list(range(1, 622)):
        falhas.append(("numeracao", "a lista nao vai de 1 a 621 sem furo", False))
    for i in itens():
        if i["status"] not in STATUS:
            falhas.append((f"item {i['n']}", f"status {i['status']} desconhecido", False))
        ref = i["ref"]
        if i["status"] in ("TEM", "PARCIAL"):
            if not ref:
                falhas.append((f"item {i['n']}", "TEM/PARCIAL sem referencia", False))
            elif ref.startswith("PR-"):
                if ref[3:5] not in caderno_nums:
                    falhas.append((f"item {i['n']}", f"referencia {ref} nao esta no caderno", False))
            elif ref.startswith("ENG:"):
                if ref[4:] not in eng_vistas:
                    falhas.append((f"item {i['n']}", f"vista {ref} nao existe", False))
            elif ref.startswith("OUT:"):
                if not os.path.exists(os.path.join(out_dir, ref[4:])):
                    falhas.append((f"item {i['n']}", f"arquivo {ref} nao existe", False))
            elif ref.startswith("DOC:"):
                if not os.path.exists(os.path.join(out_dir, "..", "docs", ref[4:] + ".md")):
                    falhas.append((f"item {i['n']}", f"documento {ref} nao existe", False))
        if i["status"] == "NA" and not (i["nota"] or i["ref"]):
            falhas.append((f"item {i['n']}", "NA sem razao", False))
        if i["status"] == "EXTERNO" and not (i["nota"] or i["ref"]):
            falhas.append((f"item {i['n']}", "EXTERNO sem dizer de quem depende", False))
        if i["sinonimo_de"] is not None:
            alvo = next((x for x in itens() if x["n"] == i["sinonimo_de"]), None)
            if alvo is None:
                falhas.append((f"item {i['n']}", f"sinonimo de {i['sinonimo_de']}, que nao existe", False))
            elif alvo["sinonimo_de"] is not None:
                falhas.append((f"item {i['n']}", f"sinonimo de sinonimo ({i['sinonimo_de']})", False))
    return falhas
